USE Webshop;
SELECT Id, Name, Price, Stock
FROM Products;

SELECT * FROM Users

SELECT * FROM ProductImages WHERE ProductId = 11 ORDER BY Id DESC;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ProductImages';
